// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareFileForSimple.DataPersistent;

#nullable disable

namespace ShareFileForSimple.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219121448_AddFileStoregeName")]
    partial class AddFileStoregeName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ShareFileForSimple.DataPersistent.Model.FileItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileRecordId");

                    b.ToTable("FileItemModels");
                });

            modelBuilder.Entity("ShareFileForSimple.DataPersistent.Model.FileRecordModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("FileRecordModels");
                });

            modelBuilder.Entity("ShareFileForSimple.DataPersistent.Model.FileItemModel", b =>
                {
                    b.HasOne("ShareFileForSimple.DataPersistent.Model.FileRecordModel", "FileRecord")
                        .WithMany("FileItems")
                        .HasForeignKey("FileRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileRecord");
                });

            modelBuilder.Entity("ShareFileForSimple.DataPersistent.Model.FileRecordModel", b =>
                {
                    b.Navigation("FileItems");
                });
#pragma warning restore 612, 618
        }
    }
}
